create table movies (
	id INT,
	name VARCHAR(50),
	year VARCHAR(50),
--	genre_id
--  director_id
);
insert into movies (id, name, year) values (1, 'As Luck Would Have It (Chispa de la vida, La)', 2007, null, null);
insert into movies (id, name, year) values (2, 'Caliber 9', 2007);
insert into movies (id, name, year) values (3, 'Green Years, The', 1992);
insert into movies (id, name, year) values (4, 'Identity Thief', 2012);
insert into movies (id, name, year) values (5, 'Communion', 2001);
insert into movies (id, name, year) values (6, 'I Shot a Man in Vegas', 2007);
insert into movies (id, name, year) values (7, 'Beyond the Law (Lain ulkopuolella)', 2007);
insert into movies (id, name, year) values (8, 'Order, The', 1993);
insert into movies (id, name, year) values (9, 'Big Trail, The', 2008);
insert into movies (id, name, year) values (10, 'Let''s Not Keep in Touch!', 1996);
insert into movies (id, name, year) values (11, 'Paragraph 175', 2010);
insert into movies (id, name, year) values (12, 'Lightning Strikes Twice', 2004);
insert into movies (id, name, year) values (13, 'Everybody''s Fine', 2006);
insert into movies (id, name, year) values (14, 'Die Frau des Frisörs', 2007);
insert into movies (id, name, year) values (15, 'Nocturna Artificialia', 1994);
insert into movies (id, name, year) values (16, 'Love Is the Devil', 1989);
insert into movies (id, name, year) values (17, 'A True Mob Story', 2000);
insert into movies (id, name, year) values (18, 'Boy, Did I Get a Wrong Number!', 2011);
insert into movies (id, name, year) values (19, 'Devil''s Brigade, The', 2007);
insert into movies (id, name, year) values (20, 'Beautiful Joe', 2011);
insert into movies (id, name, year) values (21, 'You Are So Beautiful (Je vous trouve très beau)', 1973);
insert into movies (id, name, year) values (22, '3 A.M.', 1998);
insert into movies (id, name, year) values (23, 'Werner - Beinhart!', 1995);
insert into movies (id, name, year) values (24, 'Blood Ties', 2011);
insert into movies (id, name, year) values (25, 'Marcello Mastroianni: I Remember Yes, I Remember (Marcello Mastroianni: mi ricordo, sì, io mi ricordo)', 2004);
insert into movies (id, name, year) values (26, 'Possession', 2007);
insert into movies (id, name, year) values (27, 'Anniversary, The', 2008);
insert into movies (id, name, year) values (28, 'Mamma Mia!', 1993);
insert into movies (id, name, year) values (29, 'Bear''s Kiss', 2006);
insert into movies (id, name, year) values (30, 'Hamsun', 2002);
insert into movies (id, name, year) values (31, 'Dream Catcher, The', 1998);
insert into movies (id, name, year) values (32, 'Reggie Watts: Why Shit So Crazy?', 1990);
insert into movies (id, name, year) values (33, 'Boy Meets Girl', 1992);
insert into movies (id, name, year) values (34, 'Hebrew Hammer, The', 2002);
insert into movies (id, name, year) values (35, 'You Don''t Mess with the Zohan', 2007);
insert into movies (id, name, year) values (36, 'Siegfried', 2009);
insert into movies (id, name, year) values (37, 'Shadowboxer', 2002);
insert into movies (id, name, year) values (38, 'Pink Panther 2, The', 1999);
insert into movies (id, name, year) values (39, 'Madame Curie', 1984);
insert into movies (id, name, year) values (40, 'Great Yokai War, The (Yôkai daisensô)', 2001);
insert into movies (id, name, year) values (41, 'Get Rich or Die Tryin''', 1977);
insert into movies (id, name, year) values (42, 'Gonzo: The Life and Work of Dr. Hunter S. Thompson', 1991);
insert into movies (id, name, year) values (43, 'Conan the Barbarian', 2012);
insert into movies (id, name, year) values (44, 'The Infinite Man', 1986);
insert into movies (id, name, year) values (45, 'Evil Dead', 2003);
insert into movies (id, name, year) values (46, 'Bedevilled (Kim Bok-nam salinsageonui jeonmal)', 2000);
insert into movies (id, name, year) values (47, 'High School Musical 3: Senior Year', 2010);
insert into movies (id, name, year) values (48, 'Dangerous Moves (La diagonale du fou)', 1994);
insert into movies (id, name, year) values (49, 'Black Field', 2010);
insert into movies (id, name, year) values (50, 'Things Are Tough All Over', 2008);
insert into movies (id, name, year) values (51, 'Man Facing Southeast (Hombre mirando al sudeste)', 2005);
insert into movies (id, name, year) values (52, 'Evil Toons', 1993);
insert into movies (id, name, year) values (53, 'Frank', 1995);
insert into movies (id, name, year) values (54, 'Fiend with the Electronic Brain (Blood of Ghastly Horror)', 1978);
insert into movies (id, name, year) values (55, 'Carbine Williams', 1999);
insert into movies (id, name, year) values (56, 'Scanners II: The New Order', 2004);
insert into movies (id, name, year) values (57, 'Renegades', 1984);
insert into movies (id, name, year) values (58, 'Lights Out', 2004);
insert into movies (id, name, year) values (59, 'Blood and Black Lace (Sei donne per l''assassino)', 2006);
insert into movies (id, name, year) values (60, 'Romantics Anonymous (Les émotifs anonymes)', 1992);
insert into movies (id, name, year) values (61, 'Tea For Two', 1993);
insert into movies (id, name, year) values (62, 'Emergency Escape, The (Wyjscie awaryjne)', 2010);
insert into movies (id, name, year) values (63, 'Tillbaka till Bromma', 1992);
insert into movies (id, name, year) values (64, 'Dolphin Tale 2', 2007);
insert into movies (id, name, year) values (65, 'Godfather, The', 1992);
insert into movies (id, name, year) values (66, 'Teknolust', 2006);
insert into movies (id, name, year) values (67, 'Good Morning, Vietnam', 2009);
insert into movies (id, name, year) values (68, 'Autumn Heart, The', 2006);
insert into movies (id, name, year) values (69, 'Seventh Heaven', 1964);
insert into movies (id, name, year) values (70, '13 Assassins (Jûsan-nin no shikaku)', 2012);
insert into movies (id, name, year) values (71, 'Shenandoah', 1994);
insert into movies (id, name, year) values (72, 'Little Big League', 2001);
insert into movies (id, name, year) values (73, '3096 Days', 2000);
insert into movies (id, name, year) values (74, 'Blood and Chocolate', 1992);
insert into movies (id, name, year) values (75, 'Mexican, The', 1995);
insert into movies (id, name, year) values (76, 'Shade', 2011);
insert into movies (id, name, year) values (77, 'Tenacious D in The Pick of Destiny', 2009);
insert into movies (id, name, year) values (78, 'Night Moves', 2010);
insert into movies (id, name, year) values (79, 'The Package', 2012);
insert into movies (id, name, year) values (80, 'Empty Nest (El nido vacío)', 2008);
insert into movies (id, name, year) values (81, 'My Friend Irma Goes West', 1968);
insert into movies (id, name, year) values (82, 'Man on Wire', 2008);
insert into movies (id, name, year) values (83, 'Mr. Woodcock', 1984);
insert into movies (id, name, year) values (84, 'DuckTales: The Movie - Treasure of the Lost Lamp', 1998);
insert into movies (id, name, year) values (85, 'Promised Land', 1992);
insert into movies (id, name, year) values (86, 'Clan of the Cave Bear, The', 2012);
insert into movies (id, name, year) values (87, 'Mr. Majestyk', 1992);
insert into movies (id, name, year) values (88, 'Lady of Chance, A', 1995);
insert into movies (id, name, year) values (89, 'Killer McCoy', 2008);
insert into movies (id, name, year) values (90, 'Maid to Order', 2002);
insert into movies (id, name, year) values (91, 'Jeanne and the Perfect Guy (Jeanne et le garçon formidable)', 2001);
insert into movies (id, name, year) values (92, 'Tickets', 2004);
insert into movies (id, name, year) values (93, 'Brimstone and Treacle', 2010);
insert into movies (id, name, year) values (94, 'Annie Get Your Gun', 2001);
insert into movies (id, name, year) values (95, 'Stories of Lost Souls', 2005);
insert into movies (id, name, year) values (96, 'Greenberg', 2007);
insert into movies (id, name, year) values (97, 'Taste of Honey, A', 2001);
insert into movies (id, name, year) values (98, 'America Before Columbus', 2012);
insert into movies (id, name, year) values (99, 'Chandni Chowk to China', 2012);
insert into movies (id, name, year) values (100, 'Spooner', 2007);
insert into movies (id, name, year) values (101, 'Shutter', 2011);
insert into movies (id, name, year) values (102, 'Fan, The', 1995);
insert into movies (id, name, year) values (103, 'Shanghai', 2008);
insert into movies (id, name, year) values (104, 'Ernest in the Army', 1984);
insert into movies (id, name, year) values (105, 'Garage, The', 1985);
insert into movies (id, name, year) values (106, 'Paradise Canyon', 1992);
insert into movies (id, name, year) values (107, 'Aspen Extreme', 2006);
insert into movies (id, name, year) values (108, 'Reclaim', 1994);
insert into movies (id, name, year) values (109, 'Mercy', 2004);
insert into movies (id, name, year) values (110, 'Equinox', 1999);
insert into movies (id, name, year) values (111, 'Mistress', 2007);
insert into movies (id, name, year) values (112, 'Living with Michael Jackson', 1992);
insert into movies (id, name, year) values (113, 'Starship Invasions', 2002);
insert into movies (id, name, year) values (114, 'Immortel (ad vitam) (Immortal)', 1993);
insert into movies (id, name, year) values (115, '(Untitled)', 1994);
insert into movies (id, name, year) values (116, 'Sherlock Holmes and the Masks of Death', 2010);
insert into movies (id, name, year) values (117, 'My Louisiana Sky', 2001);
insert into movies (id, name, year) values (118, 'Deja Vu', 1984);
insert into movies (id, name, year) values (119, 'Somebody to Love', 2006);
insert into movies (id, name, year) values (120, 'Crucible, The', 2010);
insert into movies (id, name, year) values (121, 'Inside the Twin Towers', 2000);
insert into movies (id, name, year) values (122, 'Welcome to the Jungle', 2005);
insert into movies (id, name, year) values (123, 'Grudge, The', 1991);
insert into movies (id, name, year) values (124, 'Stars Fell on Henrietta, The', 1985);
insert into movies (id, name, year) values (125, 'Evangelion: 3.0 You Can (Not) Redo', 2000);
insert into movies (id, name, year) values (126, 'High School Musical 2', 1994);
insert into movies (id, name, year) values (127, 'Dirt', 2010);
insert into movies (id, name, year) values (128, 'White Lightning', 1994);
insert into movies (id, name, year) values (129, '4', 1994);
insert into movies (id, name, year) values (130, 'Patriots, The (Patriotes, Les)', 1995);
insert into movies (id, name, year) values (131, 'Bikini Summer III - South Beach Heat', 2009);
insert into movies (id, name, year) values (132, 'Suomisen Olli yllättää', 1994);
insert into movies (id, name, year) values (133, 'Rush', 1969);
insert into movies (id, name, year) values (134, 'Ladies and Gentlemen, the Fabulous Stains (a.k.a. All Washed Up)', 1991);
insert into movies (id, name, year) values (135, 'Patrik Age 1.5 (Patrik 1,5)', 2006);
insert into movies (id, name, year) values (136, 'Persona', 2004);
insert into movies (id, name, year) values (137, 'Diary for Timothy, A', 2006);
insert into movies (id, name, year) values (138, 'Man in the Saddle', 2012);
insert into movies (id, name, year) values (139, 'Halloween: The Curse of Michael Myers (Halloween 6: The Curse of Michael Myers)', 2007);
insert into movies (id, name, year) values (140, 'Beastly', 1987);
insert into movies (id, name, year) values (141, 'Bloody Sunday', 2010);
insert into movies (id, name, year) values (142, 'Billy the Kid vs. Dracula', 2004);
insert into movies (id, name, year) values (143, 'Gentlemen Prefer Blondes', 1994);
insert into movies (id, name, year) values (144, 'Four Eyes and Six-Guns', 1995);
insert into movies (id, name, year) values (145, 'Scott Pilgrim vs. the World', 2007);
insert into movies (id, name, year) values (146, 'Goodbye Solo', 2011);
insert into movies (id, name, year) values (147, 'Sasayaki (a.k.a. Moonlight Whispers) (Gekkô no sasayaki)', 1993);
insert into movies (id, name, year) values (148, 'Benny''s Video', 2001);
insert into movies (id, name, year) values (149, 'Mahler', 2000);
insert into movies (id, name, year) values (150, 'Last Winter (L''hiver dernier)', 2000);
insert into movies (id, name, year) values (151, 'Shape of Things to Come, The', 2008);
insert into movies (id, name, year) values (152, 'Undocumented', 2008);
insert into movies (id, name, year) values (153, 'Plan 9 from Outer Space', 2007);
insert into movies (id, name, year) values (154, 'Fast & Furious (Fast and the Furious 4, The)', 2003);
insert into movies (id, name, year) values (155, 'The Fox and the Hound 2', 2003);
insert into movies (id, name, year) values (156, 'Never Talk to Strangers', 2000);
insert into movies (id, name, year) values (157, 'Gen-Y Cops (Te jing xin ren lei 2) (Gen-X Cops 2: Metal Mayhem) (Metal Mayhem)', 1998);
insert into movies (id, name, year) values (158, 'White Shadows in the South Seas', 2008);
insert into movies (id, name, year) values (159, 'Sione''s Wedding (Samoan Wedding)', 1996);
insert into movies (id, name, year) values (160, 'Man Who Loved Women, The (Homme qui aimait les femmes, L'')', 2007);
insert into movies (id, name, year) values (161, 'Ain''t in It for My Health: A Film About Levon Helm', 2008);
insert into movies (id, name, year) values (162, 'Hey Ram', 1985);
insert into movies (id, name, year) values (163, 'Night at the Opera, A', 2008);
insert into movies (id, name, year) values (164, 'Day the Earth Stood Still, The', 1993);
insert into movies (id, name, year) values (165, 'Ill-Fated Love (Doomed Love) (Amor de Perdição)', 1990);
insert into movies (id, name, year) values (166, 'Last Man on Earth, The (Ultimo uomo della Terra, L'')', 2004);
insert into movies (id, name, year) values (167, 'Armed and Dangerous', 2004);
insert into movies (id, name, year) values (168, 'Gentlemen of Fortune (Dzhentlmeny udachi)', 2006);
insert into movies (id, name, year) values (169, 'Four Ways Out', 1986);
insert into movies (id, name, year) values (170, 'Heavens Fall', 2001);
insert into movies (id, name, year) values (171, 'Club Dread', 2006);
insert into movies (id, name, year) values (172, 'Daughters of the Dust', 2007);
insert into movies (id, name, year) values (173, 'Whole Nine Yards, The', 2010);
insert into movies (id, name, year) values (174, 'Robot Jox', 1995);
insert into movies (id, name, year) values (175, 'Crossfire Hurricane', 1995);
insert into movies (id, name, year) values (176, 'Moonwalker', 2001);
insert into movies (id, name, year) values (177, 'Target', 2000);
insert into movies (id, name, year) values (178, 'Wicker Man, The', 1992);
insert into movies (id, name, year) values (179, 'Film Noir: Bringing Darkness to Light', 2011);
insert into movies (id, name, year) values (180, 'Code 46', 1960);
insert into movies (id, name, year) values (181, 'Legalese', 1997);
insert into movies (id, name, year) values (182, 'Winter Passing', 1993);
insert into movies (id, name, year) values (183, 'Life and Debt', 2008);
insert into movies (id, name, year) values (184, '2001: A Space Odyssey', 2008);
insert into movies (id, name, year) values (185, 'I Am Maria (Jag är Maria)', 2007);
insert into movies (id, name, year) values (186, 'Crack-Up', 2005);
insert into movies (id, name, year) values (187, 'Lady and the Tramp', 1992);
insert into movies (id, name, year) values (188, 'Vanya on 42nd Street', 1994);
insert into movies (id, name, year) values (189, 'Invasion of the Body Snatchers', 1989);
insert into movies (id, name, year) values (190, 'Keys to the House, The (Chiavi di casa, Le)', 1992);
insert into movies (id, name, year) values (191, 'Down to Earth', 2008);
insert into movies (id, name, year) values (192, 'Profession of Arms, The (Il mestiere delle armi)', 1984);
insert into movies (id, name, year) values (193, 'Easy Living', 1990);
insert into movies (id, name, year) values (194, 'Kid With a Bike, The (Le gamin au vélo)', 1997);
insert into movies (id, name, year) values (195, 'Diving Bell and the Butterfly, The (Scaphandre et le papillon, Le)', 2005);
insert into movies (id, name, year) values (196, 'Man with One Red Shoe, The', 1986);
insert into movies (id, name, year) values (197, 'Babylon 5: A Call to Arms', 2000);
insert into movies (id, name, year) values (198, 'Lost Thing, The', 1995);
insert into movies (id, name, year) values (199, 'Idle Hands', 2005);
insert into movies (id, name, year) values (200, 'Chris Rock: Bring the Pain', 1993);
insert into movies (id, name, year) values (201, 'Zaat', 2012);
insert into movies (id, name, year) values (202, 'L''Italien', 2006);
insert into movies (id, name, year) values (203, 'Purpose', 1979);
insert into movies (id, name, year) values (204, 'Tender Mercies', 1996);
insert into movies (id, name, year) values (205, 'Skirt Day (La journée de la jupe)', 1999);
insert into movies (id, name, year) values (206, 'Uncle Boonmee Who Can Recall His Past Lives (Loong Boonmee raleuk chat)', 2001);
insert into movies (id, name, year) values (207, 'Accused, The', 1995);
insert into movies (id, name, year) values (208, 'The Finzi Detective Agency', 2009);
insert into movies (id, name, year) values (209, 'Flight Command', 2000);
insert into movies (id, name, year) values (210, 'Paper, The', 2002);
insert into movies (id, name, year) values (211, 'Dispatch from Reuter''s, A', 2012);
insert into movies (id, name, year) values (212, 'Green Room, The (a.k.a. Vanishing Fiancee) (La chambre verte)', 2008);
insert into movies (id, name, year) values (213, 'Open Road, The', 2008);
insert into movies (id, name, year) values (214, 'Lady Vanishes, The', 1998);
insert into movies (id, name, year) values (215, 'Fine Pair, A (Ruba al prossimo tuo)', 2002);
insert into movies (id, name, year) values (216, 'Family Guy Presents Stewie Griffin: The Untold Story', 1994);
insert into movies (id, name, year) values (217, 'Hanky Panky', 1969);
insert into movies (id, name, year) values (218, 'Drugstore Cowboy', 2003);
insert into movies (id, name, year) values (219, 'The Cop in Blue Jeans', 2011);
insert into movies (id, name, year) values (220, 'Marriage Retreat', 1993);
insert into movies (id, name, year) values (221, 'Nosferatu the Vampyre (Nosferatu: Phantom der Nacht)', 2004);
insert into movies (id, name, year) values (222, 'Guys, The', 2002);
insert into movies (id, name, year) values (223, 'Blablablá', 2005);
insert into movies (id, name, year) values (224, 'Agnes Browne', 2005);
insert into movies (id, name, year) values (225, 'Bionicle: Mask of Light (Bionicle: Mask of Light - The Movie)', 1994);
insert into movies (id, name, year) values (226, 'Klimt', 2004);
insert into movies (id, name, year) values (227, 'Dunwich Horror, The', 2008);
insert into movies (id, name, year) values (228, 'At Land', 1993);
insert into movies (id, name, year) values (229, 'Weight of the Nation', 1992);
insert into movies (id, name, year) values (230, 'White Massai, The (Weisse Massai, Die)', 1984);
insert into movies (id, name, year) values (231, 'Galapagos Affair: Satan Came to Eden, The', 2007);
insert into movies (id, name, year) values (232, 'Conspiracy', 2012);
insert into movies (id, name, year) values (233, 'Beowulf', 1992);
insert into movies (id, name, year) values (234, 'Psycho II', 2004);
insert into movies (id, name, year) values (235, 'Beverly Hills Chihuahua 2', 2011);
insert into movies (id, name, year) values (236, 'Grandmaster, The (Yi dai zong shi)', 2009);
insert into movies (id, name, year) values (237, 'Year One', 1993);
insert into movies (id, name, year) values (238, 'Iria: Zeiram the Animation ', 1997);
insert into movies (id, name, year) values (239, 'Just Married', 2007);
insert into movies (id, name, year) values (240, 'Macross Plus', 2002);
insert into movies (id, name, year) values (241, 'Da Vinci Code, The', 1988);
insert into movies (id, name, year) values (242, 'Forbidden Games (Jeux interdits)', 1988);
insert into movies (id, name, year) values (243, 'Life of Aleksis Kivi, The (Aleksis Kiven elämä)', 1993);
insert into movies (id, name, year) values (244, 'Carandiru', 1996);
insert into movies (id, name, year) values (245, 'Monster Club, The', 2007);
insert into movies (id, name, year) values (246, 'Breakaway (Speedy Singhs)', 2002);
insert into movies (id, name, year) values (247, 'Harem', 2003);
insert into movies (id, name, year) values (248, 'Asterix vs. Caesar (Astérix et la surprise de César)', 2008);
insert into movies (id, name, year) values (249, 'Miracle on 34th Street', 2006);
insert into movies (id, name, year) values (250, 'Racing Dreams', 2011);
insert into movies (id, name, year) values (251, 'U-571', 2005);
insert into movies (id, name, year) values (252, 'Radio Rebel', 2003);
insert into movies (id, name, year) values (253, 'Batman', 1993);
insert into movies (id, name, year) values (254, 'Walking with Monsters', 2007);
insert into movies (id, name, year) values (255, 'Ditirambo', 2008);
insert into movies (id, name, year) values (256, 'Force of Evil', 2002);
insert into movies (id, name, year) values (257, 'Pekka ja Pätkä salapoliiseina', 2003);
insert into movies (id, name, year) values (258, 'The Green Prince', 1987);
insert into movies (id, name, year) values (259, 'Kidnapped', 2007);
insert into movies (id, name, year) values (260, 'Warrior', 1992);
insert into movies (id, name, year) values (261, 'Love & Savagery', 1998);
insert into movies (id, name, year) values (262, 'Downstairs', 2011);
insert into movies (id, name, year) values (263, 'Scavenger Hunt', 2007);
insert into movies (id, name, year) values (264, 'Light Years Away', 2006);
insert into movies (id, name, year) values (265, 'Strada, La', 2011);
insert into movies (id, name, year) values (266, 'Funeral, The (Ososhiki)', 2002);
insert into movies (id, name, year) values (267, 'Saw', 1966);
insert into movies (id, name, year) values (268, 'Balls Out: Gary the Tennis Coach', 2000);
insert into movies (id, name, year) values (269, 'Aladin', 2007);
insert into movies (id, name, year) values (270, 'Story of Marie and Julien, The (Histoire de Marie et Julien)', 1991);
insert into movies (id, name, year) values (271, 'Pascali''s Island', 1967);
insert into movies (id, name, year) values (272, 'Killing Us Softly 3', 2004);
insert into movies (id, name, year) values (273, 'Big Red One, The', 1992);
insert into movies (id, name, year) values (274, 'Singles', 2009);
insert into movies (id, name, year) values (275, 'Woodstock', 1986);
insert into movies (id, name, year) values (276, 'Little Miss Broadway', 1995);
insert into movies (id, name, year) values (277, 'Sphere', 1994);
insert into movies (id, name, year) values (278, 'See No Evil', 2012);
insert into movies (id, name, year) values (279, 'Generation X', 1998);
insert into movies (id, name, year) values (280, 'Caller, The', 1992);
insert into movies (id, name, year) values (281, 'Beverly Hills Cop', 2008);
insert into movies (id, name, year) values (282, 'Triumph of the Will (Triumph des Willens)', 1969);
insert into movies (id, name, year) values (283, 'Cup, The (Phörpa)', 1972);
insert into movies (id, name, year) values (284, 'Montana Sky', 1969);
insert into movies (id, name, year) values (285, 'What the Day Owes the Night', 1996);
insert into movies (id, name, year) values (286, 'Love unto Death (L''amour a mort)', 2012);
insert into movies (id, name, year) values (287, 'Home Sweet Hell', 2001);
insert into movies (id, name, year) values (288, 'Blackwoods', 1993);
insert into movies (id, name, year) values (289, 'Return of the Living Dead: Rave to the Grave', 1999);
insert into movies (id, name, year) values (290, 'Black Angel', 1989);
insert into movies (id, name, year) values (291, 'Art of Crying, The (Kunsten at græde i kor)', 1993);
insert into movies (id, name, year) values (292, 'Went to Coney Island on a Mission From God... Be Back by Five', 2006);
insert into movies (id, name, year) values (293, 'Portraits Chinois', 2003);
insert into movies (id, name, year) values (294, 'Superman and the Mole-Men', 1990);
insert into movies (id, name, year) values (295, 'Burnt by the Sun (Utomlyonnye solntsem)', 2006);
insert into movies (id, name, year) values (296, 'White Hunter, Black Heart', 2000);
insert into movies (id, name, year) values (297, 'Justice League: The New Frontier ', 1998);
insert into movies (id, name, year) values (298, 'Black Fury', 1999);
insert into movies (id, name, year) values (299, 'Case Against 8, The', 1967);
insert into movies (id, name, year) values (300, 'Cradle Will Rock', 2008);
insert into movies (id, name, year) values (301, 'Call Me Crazy: A Five Film', 2010);
insert into movies (id, name, year) values (302, 'Trouble with the Curve', 2004);
insert into movies (id, name, year) values (303, 'Private School', 2000);
insert into movies (id, name, year) values (304, 'Omega Man, The', 2009);
insert into movies (id, name, year) values (305, 'Grouse', 2002);
insert into movies (id, name, year) values (306, 'Witchboard', 1991);
insert into movies (id, name, year) values (307, '7500', 1989);
insert into movies (id, name, year) values (308, 'Gagarin: First in Space', 2004);
insert into movies (id, name, year) values (309, 'Neverwas', 1996);
insert into movies (id, name, year) values (310, 'Good Morning, Vietnam', 2002);
insert into movies (id, name, year) values (311, 'Fresh', 1994);
insert into movies (id, name, year) values (312, 'Die Bademeister – Weiber, saufen, Leben retten', 1998);
insert into movies (id, name, year) values (313, 'Begone Dull Care', 1987);
insert into movies (id, name, year) values (314, 'Me and You and Everyone We Know', 1963);
insert into movies (id, name, year) values (315, 'Anatomy of Hell (Anatomie de l''enfer)', 1986);
insert into movies (id, name, year) values (316, 'Category 7: The End of the World', 1998);
insert into movies (id, name, year) values (317, 'Fall, The', 2001);
insert into movies (id, name, year) values (318, 'Bertsolari', 1997);
insert into movies (id, name, year) values (319, 'Americano', 1991);
insert into movies (id, name, year) values (320, 'Not Love, Just Frenzy (Más que amor, frenesí)', 1997);
insert into movies (id, name, year) values (321, 'Buddha Collapsed Out of Shame', 2011);
insert into movies (id, name, year) values (322, 'Beverly Hills Chihuahua 2', 1976);
insert into movies (id, name, year) values (323, 'Big Bang Love, Juvenile A (46-okunen no koi)', 1988);
insert into movies (id, name, year) values (324, 'Wyatt Earp', 2011);
insert into movies (id, name, year) values (325, 'We Still Kill the Old Way', 2006);
insert into movies (id, name, year) values (326, 'Future Cops (Chao ji xue xiao ba wang)', 2003);
insert into movies (id, name, year) values (327, 'Adaptation', 2007);
insert into movies (id, name, year) values (328, 'Into the Blue 2: The Reef', 1996);
insert into movies (id, name, year) values (329, 'Bread and Alley (Nan va Koutcheh)', 2008);
insert into movies (id, name, year) values (330, 'Every Which Way But Loose', 1990);
insert into movies (id, name, year) values (331, 'The Eagle and the Hawk', 1992);
insert into movies (id, name, year) values (332, 'Man from London, The (A Londoni férfi)', 2012);
insert into movies (id, name, year) values (333, 'Train on the Brain', 2006);
insert into movies (id, name, year) values (334, 'Children On Their Birthdays', 1993);
insert into movies (id, name, year) values (335, 'Royal Scandal, A', 2004);
insert into movies (id, name, year) values (336, 'Low Down Dirty Shame, A', 1993);
insert into movies (id, name, year) values (337, 'Star Trek V: The Final Frontier', 1997);
insert into movies (id, name, year) values (338, 'Chill Out! (Descongélate!)', 1992);
insert into movies (id, name, year) values (339, 'Puffy Chair, The', 1988);
insert into movies (id, name, year) values (340, 'V: The Final Battle', 2007);
insert into movies (id, name, year) values (341, 'Bad Company', 2005);
insert into movies (id, name, year) values (342, 'Cain and Mabel', 1986);
insert into movies (id, name, year) values (343, 'The King and Four Queens', 2012);
insert into movies (id, name, year) values (344, 'Secret Agent', 1997);
insert into movies (id, name, year) values (345, 'Longest Yard, The', 2008);
insert into movies (id, name, year) values (346, 'Films to Keep You Awake: The Baby''s Room (Películas para no dormir: La habitación del niño)', 1995);
insert into movies (id, name, year) values (347, 'Soundbreaker ', 1992);
insert into movies (id, name, year) values (348, 'Son of the Bride (Hijo de la novia, El)', 1993);
insert into movies (id, name, year) values (349, 'Action Jackson', 1999);
insert into movies (id, name, year) values (350, 'Sleepaway Camp', 1998);
insert into movies (id, name, year) values (351, 'Charlotte''s Web', 1999);
insert into movies (id, name, year) values (352, 'Body/Cialo', 1995);
insert into movies (id, name, year) values (353, 'Raiders From Beneath the Sea', 2003);
insert into movies (id, name, year) values (354, 'Tarnished Angels, The', 2001);
insert into movies (id, name, year) values (355, 'Manos: The Hands of Fate', 2008);
insert into movies (id, name, year) values (356, 'Hipsters (Stilyagi)', 2004);
insert into movies (id, name, year) values (357, 'Stand, The', 2001);
insert into movies (id, name, year) values (358, 'American Tail, An', 2011);
insert into movies (id, name, year) values (359, 'Westfront 1918', 2008);
insert into movies (id, name, year) values (360, 'Autohystoria', 1992);
insert into movies (id, name, year) values (361, 'Freeway II: Confessions of a Trickbaby', 1998);
insert into movies (id, name, year) values (362, 'Onion Field, The', 2002);
insert into movies (id, name, year) values (363, 'Drama/Mex', 1991);
insert into movies (id, name, year) values (364, 'Phantasm II', 1996);
insert into movies (id, name, year) values (365, 'Eat Drink Man Woman (Yin shi nan nu)', 2001);
insert into movies (id, name, year) values (366, 'Auschwitz: The Nazis and the ''Final Solution''', 2008);
insert into movies (id, name, year) values (367, 'Kicking and Screaming', 1999);
insert into movies (id, name, year) values (368, 'Lone Wolf and Cub: Baby Cart at the River Styx (Kozure Ôkami: Sanzu no kawa no ubaguruma)', 2002);
insert into movies (id, name, year) values (369, 'Sharpe''s Eagle', 1989);
insert into movies (id, name, year) values (370, 'Undisputed', 1993);
insert into movies (id, name, year) values (371, 'Mexican Hayride', 1995);
insert into movies (id, name, year) values (372, 'My Mom Is a Character (Minha Mãe é uma Peça: O Filme)', 2005);
insert into movies (id, name, year) values (373, 'Familia', 2006);
insert into movies (id, name, year) values (374, 'It Happened at the World''s Fair', 1985);
insert into movies (id, name, year) values (375, 'Faces of Death 2', 2010);
insert into movies (id, name, year) values (376, 'Transformers: Age of Extinction', 2004);
insert into movies (id, name, year) values (377, 'Ghosts of Mississippi', 2009);
insert into movies (id, name, year) values (378, 'Saving Face', 1992);
insert into movies (id, name, year) values (379, 'Die Bademeister – Weiber, saufen, Leben retten', 1990);
insert into movies (id, name, year) values (380, 'Generation Kill', 2006);
insert into movies (id, name, year) values (381, 'Vääpeli Körmy ja marsalkan sauva', 1987);
insert into movies (id, name, year) values (382, 'Headless Body in Topless Bar', 1995);
insert into movies (id, name, year) values (383, 'Mr. & Mrs. Bridge', 1992);
insert into movies (id, name, year) values (384, 'Adjuster, The', 1996);
insert into movies (id, name, year) values (385, 'Crush', 1987);
insert into movies (id, name, year) values (386, 'Shark Skin Man and Peach Hip Girl (Samehada otoko to momojiri onna)', 1996);
insert into movies (id, name, year) values (387, 'Meet Me at the Fair', 2005);
insert into movies (id, name, year) values (388, 'Hedd Wyn', 1983);
insert into movies (id, name, year) values (389, 'Cinema Paradiso (Nuovo cinema Paradiso)', 1992);
insert into movies (id, name, year) values (390, 'Music Man, The', 1997);
insert into movies (id, name, year) values (391, 'Gumby: The Movie', 1985);
insert into movies (id, name, year) values (392, 'Manito', 2002);
insert into movies (id, name, year) values (393, 'Smokers Only (Vagón Fumador)', 2006);
insert into movies (id, name, year) values (394, 'Three Stooges in Orbit, The', 2013);
insert into movies (id, name, year) values (395, 'Princess Aurora (Orora gongju)', 1996);
insert into movies (id, name, year) values (396, 'Man of Aran', 2007);
insert into movies (id, name, year) values (397, 'New York', 2003);
insert into movies (id, name, year) values (398, 'Slappy and the Stinkers', 2006);
insert into movies (id, name, year) values (399, 'Long Gray Line, The', 2004);
insert into movies (id, name, year) values (400, 'Chronicles of Narnia: Prince Caspian, The', 1985);
insert into movies (id, name, year) values (401, 'I Know What You Did Last Summer', 1997);
insert into movies (id, name, year) values (402, 'Mahabharata, The', 1992);
insert into movies (id, name, year) values (403, 'Stake Land', 1999);
insert into movies (id, name, year) values (404, 'After Tiller', 2009);
insert into movies (id, name, year) values (405, 'That Uncertain Feeling', 1997);
insert into movies (id, name, year) values (406, 'Analyze That', 1996);
insert into movies (id, name, year) values (407, 'Owning Mahowny', 2002);
insert into movies (id, name, year) values (408, 'Something''s Gonna Live', 2008);
insert into movies (id, name, year) values (409, 'Hunting and Gathering (Ensemble, c''est tout)', 1995);
insert into movies (id, name, year) values (410, 'My Perestroika', 1992);
insert into movies (id, name, year) values (411, 'Actress, The', 1993);
insert into movies (id, name, year) values (412, 'Dragon Gate Inn (Dragon Inn) (Long men kezhan)', 2007);
insert into movies (id, name, year) values (413, 'Near Dark', 1984);
insert into movies (id, name, year) values (414, 'God''s Little Acre', 1992);
insert into movies (id, name, year) values (415, 'Hot Rock, The', 2011);
insert into movies (id, name, year) values (416, 'Where Angels Fear to Tread', 2004);
insert into movies (id, name, year) values (417, 'Mayerling', 1962);
insert into movies (id, name, year) values (418, 'Birdcage Inn (Paran daemun)', 2009);
insert into movies (id, name, year) values (419, 'Twilight Saga: New Moon, The', 1992);
insert into movies (id, name, year) values (420, 'Sunset', 2007);
insert into movies (id, name, year) values (421, 'Dirty Mary Crazy Larry', 2007);
insert into movies (id, name, year) values (422, 'Earthsea (Legend of Earthsea)', 1992);
insert into movies (id, name, year) values (423, 'Hybrid', 2008);
insert into movies (id, name, year) values (424, 'Ambition', 2010);
insert into movies (id, name, year) values (425, 'Danika', 2001);
insert into movies (id, name, year) values (426, 'Devil''s Double, The', 1990);
insert into movies (id, name, year) values (427, 'House Party 3', 2011);
insert into movies (id, name, year) values (428, 'Stolen Kisses (Baisers volés)', 1998);
insert into movies (id, name, year) values (429, 'Coup de grâce (Der Fangschuß)', 2008);
insert into movies (id, name, year) values (430, 'Get Educated: Paathshaala', 2007);
insert into movies (id, name, year) values (431, 'Macbeth (a.k.a. Tragedy of Macbeth, The)', 1989);
insert into movies (id, name, year) values (432, '88 Minutes', 1992);
insert into movies (id, name, year) values (433, 'Forgiving Dr. Mengele', 2009);
insert into movies (id, name, year) values (434, 'Softening of the Egg, The (Ägget är löst!)', 2011);
insert into movies (id, name, year) values (435, 'Stoic', 2000);
insert into movies (id, name, year) values (436, 'Portrait Werner Herzog', 1996);
insert into movies (id, name, year) values (437, 'Core, The', 1985);
insert into movies (id, name, year) values (438, 'Dream (Bi-mong)', 2002);
insert into movies (id, name, year) values (439, 'Waterloo Bridge', 2007);
insert into movies (id, name, year) values (440, 'Doctor Strange', 2007);
insert into movies (id, name, year) values (441, 'Scott Walker: 30 Century Man', 1985);
insert into movies (id, name, year) values (442, 'Girl of Finland (Lapualaismorsian)', 1983);
insert into movies (id, name, year) values (443, 'Trials of Cate McCall, The', 1994);
insert into movies (id, name, year) values (444, 'Taking Sides', 1997);
insert into movies (id, name, year) values (445, 'It Happened on Fifth Avenue', 2001);
insert into movies (id, name, year) values (446, 'Inuyasha the Movie: The Castle Beyond the Looking Glass', 1991);
insert into movies (id, name, year) values (447, 'Journey to the Far Side of the Sun (a.k.a. Doppelgänger)', 1993);
insert into movies (id, name, year) values (448, 'Schlussmacher', 2004);
insert into movies (id, name, year) values (449, 'Sisterhood of the Traveling Pants 2, The', 1997);
insert into movies (id, name, year) values (450, 'Sacro GRA', 2002);
insert into movies (id, name, year) values (451, 'Ultramarines: A Warhammer 40,000 Movie', 2001);
insert into movies (id, name, year) values (452, 'The Expedition to the End of the World', 1996);
insert into movies (id, name, year) values (453, '5 Broken Cameras', 1996);
insert into movies (id, name, year) values (454, 'Children of Huang Shi, The', 2010);
insert into movies (id, name, year) values (455, 'Cheech & Chong''s Next Movie', 2012);
insert into movies (id, name, year) values (456, 'French Fried Vacation 2 (Les bronzés font du ski)', 2008);
insert into movies (id, name, year) values (457, 'Night of the Living Dorks', 1999);
insert into movies (id, name, year) values (458, 'Manta, Manta', 2006);
insert into movies (id, name, year) values (459, 'Guerrilla: The Taking of Patty Hearst', 1999);
insert into movies (id, name, year) values (460, 'First Name: Carmen (Prénom Carmen)', 2012);
insert into movies (id, name, year) values (461, 'You Can''t Win ''Em All', 2000);
insert into movies (id, name, year) values (462, 'Never Forever', 2011);
insert into movies (id, name, year) values (463, 'Blood Spattered Bride, The (La novia ensangrentada)', 2012);
insert into movies (id, name, year) values (464, 'Animal Room', 1999);
insert into movies (id, name, year) values (465, 'Against All Odds', 2007);
insert into movies (id, name, year) values (466, 'Midnight Run', 2001);
insert into movies (id, name, year) values (467, 'Boogie Nights', 2007);
insert into movies (id, name, year) values (468, 'Lipstick', 2008);
insert into movies (id, name, year) values (469, 'Taxi Driver', 1992);
insert into movies (id, name, year) values (470, 'Crime at Porta Romana', 2007);
insert into movies (id, name, year) values (471, 'Ivans xtc.', 2006);
insert into movies (id, name, year) values (472, 'North West Frontier', 1992);
insert into movies (id, name, year) values (473, 'Passion Flower', 1968);
insert into movies (id, name, year) values (474, 'Barefoot (Barfuss)', 2011);
insert into movies (id, name, year) values (475, 'Wedding Night, The', 2010);
insert into movies (id, name, year) values (476, 'Carry on Behind', 1948);
insert into movies (id, name, year) values (477, 'Year of the Dragon', 2006);
insert into movies (id, name, year) values (478, 'Blackout', 2001);
insert into movies (id, name, year) values (479, 'Compulsion', 2007);
insert into movies (id, name, year) values (480, 'Stevie', 1958);
insert into movies (id, name, year) values (481, 'Godzilla, King of the Monsters! (Kaijû-ô Gojira)', 2006);
insert into movies (id, name, year) values (482, 'SS Experiment Love Camp (Lager SSadis Kastrat Kommandantur)', 1998);
insert into movies (id, name, year) values (483, 'Party 2, The (Boum 2, La)', 1988);
insert into movies (id, name, year) values (484, 'Dangerous Liaisons', 1997);
insert into movies (id, name, year) values (485, 'Rules of Attraction, The', 1995);
insert into movies (id, name, year) values (486, 'House by the Cemetery, The (Quella villa accanto al cimitero)', 2005);
insert into movies (id, name, year) values (487, 'Incredible Journey, The', 2012);
insert into movies (id, name, year) values (488, 'Dead Poets Society', 2010);
insert into movies (id, name, year) values (489, 'Turkish Passion (La pasión turca)', 2004);
insert into movies (id, name, year) values (490, 'Israeli Intelligence (Hamosad Hasagur)', 1999);
insert into movies (id, name, year) values (491, 'Implanted', 1992);
insert into movies (id, name, year) values (492, 'Chamber, The', 2005);
insert into movies (id, name, year) values (493, 'Abyss, The', 2006);
insert into movies (id, name, year) values (494, 'Bad Ass', 2007);
insert into movies (id, name, year) values (495, 'Examined Life', 2009);
insert into movies (id, name, year) values (496, 'Journey, The', 1998);
insert into movies (id, name, year) values (497, 'Queen of the Damned', 2008);
insert into movies (id, name, year) values (498, 'Final Season, The', 2006);
insert into movies (id, name, year) values (499, 'Dream (Bi-mong)', 2003);
insert into movies (id, name, year) values (500, 'Sealed Cargo', 1963);
